# Understanding Faiss

In [1]:
# #Install Packages
# !pip install faiss-cpu
# !pip install sentence-transformers

In [2]:
# import pandas 
import pandas as pd 

In [3]:
df = pd.read_csv("FAISS_text.csv")

In [4]:
df

text category
0      Meditation and yoga can improve mental health   Health
1  Fruits, whole grains and vegetables helps cont...   Health
2  These are the latest fashion trends for this week  Fashion
3  Vibrant color jeans for male are becoming a trend  Fashion
4                 The concert starts at 7 PM tonight    Event
5  Navaratri dandiya program at Expo center in Mu...    Event
6  Exciting vacation destinations for your next trip   Travel
7  Maldives and Srilanka are gaining popularity i...   Travel

In [5]:
# Converting the text to vector using embeddings 

from sentence_transformers import SentenceTransformer

C:\Users\teja8\AppData\Local\Programs\Python\Python312\Lib\site-packages\sentence_transformers\cross_encoder\CrossEncoder.py:11: TqdmExperimentalWarning: Using `tqdm.autonotebook.tqdm` in notebook mode. Use `tqdm.tqdm` instead to force console mode (e.g. in jupyter console)
  from tqdm.autonotebook import tqdm, trange


In [6]:
# Hugging face encoder 
encoder = SentenceTransformer("all-mpnet-base-v2")
vectors = encoder.encode(df.text)

C:\Users\teja8\AppData\Local\Programs\Python\Python312\Lib\site-packages\transformers\tokenization_utils_base.py:1601: FutureWarning: `clean_up_tokenization_spaces` was not set. It will be set to `True` by default. This behavior will be depracted in transformers v4.45, and will be then set to `False` by default. For more details check this issue: https://github.com/huggingface/transformers/issues/31884
  warnings.warn(


In [7]:
vectors

array([[-0.00247395,  0.03626721, -0.05290459, ..., -0.09152356,
        -0.03970002, -0.04330488],
       [-0.03357267,  0.00980517, -0.03250129, ..., -0.05165467,
         0.02245886, -0.03156182],
       [-0.01865323, -0.04051314, -0.01235387, ...,  0.00610585,
        -0.07179647,  0.02773853],
       ...,
       [-0.00066458,  0.04252125, -0.05645508, ...,  0.01315471,
        -0.03183568, -0.04357664],
       [-0.03317154,  0.03252455, -0.02484838, ...,  0.01174421,
         0.05747123,  0.00571021],
       [-0.00166395,  0.00413827, -0.04597082, ...,  0.02008527,
         0.05656242, -0.00161595]], dtype=float32)

In [8]:
vectors.shape

(8, 768)

In [9]:
vectors[0]

array([-2.47395248e-03,  3.62672098e-02, -5.29045872e-02, -2.17348319e-02,
        1.41723454e-02, -1.01600331e-03,  2.23637372e-02,  3.65196317e-02,
        3.80901434e-02,  5.22007467e-03, -3.00865676e-02,  2.05450621e-03,
        1.08502982e-02, -8.49087834e-02, -5.57269482e-03, -6.06597736e-02,
        2.32009869e-03, -1.51409162e-02,  1.20670889e-02,  1.98905114e-02,
       -1.27936164e-02, -2.72811316e-02, -3.31878588e-02,  3.40648624e-03,
        8.41166917e-03, -1.94855332e-02,  4.88132089e-02,  2.24118270e-02,
        4.53466661e-02, -5.90892285e-02, -9.13182199e-02, -1.22332934e-03,
       -4.05045897e-02,  8.67188256e-03,  1.26565260e-06, -1.92451514e-02,
       -3.20659392e-02, -4.08172458e-02,  8.79177079e-02, -1.52632259e-02,
        1.09908832e-02, -4.47976924e-02, -4.74822242e-03,  3.52632254e-02,
        1.31070735e-02,  1.09944055e-02, -3.45762307e-03,  9.12349299e-02,
        5.68809770e-02,  4.82893623e-02, -4.51437850e-03,  3.58451270e-02,
       -2.44210232e-02, -

In [10]:
dim = vectors.shape[1]

In [11]:
dim

768

In [12]:
import faiss
index = faiss.IndexFlatL2(dim)

In [13]:
index


<faiss.swigfaiss_avx2.IndexFlatL2; proxy of <Swig Object of type 'faiss::IndexFlatL2 *' at 0x0000017D01312760> >

In [14]:
index.add(vectors)

In [15]:
search_query = "i love black shirts"

In [16]:
vec = encoder.encode(search_query)

In [17]:
vec.shape

(768,)

In [18]:
import numpy as np 
svec = np.array(vec).reshape(1,-1)

In [19]:
svec.shape

(1, 768)

In [20]:
index.search(svec, k=2)

(array([[1.081248 , 1.3583515]], dtype=float32), array([[3, 2]], dtype=int64))

In [21]:
dis, I = index.search(svec, k=2)

In [22]:
dis

array([[1.081248 , 1.3583515]], dtype=float32)

In [23]:
I

array([[3, 2]], dtype=int64)

In [24]:
df.loc[I[0]]

text category
3  Vibrant color jeans for male are becoming a trend  Fashion
2  These are the latest fashion trends for this week  Fashion